// KARAT Assessment prep - role-specific study guides and practice questions.
// Content (not certifications): a guide of key topics plus role-specific Q&A.

export const KARAT_TRACKS = [
  {
    id: 'devops',
    label: 'DevOps',
    blurb: 'CI/CD, containers, orchestration, infrastructure-as-code, observability and cloud.',
    guide: [
      { topic: 'CI/CD Pipelines', detail: 'Automate build → test → deploy with gating and rollback. Know stages, artifacts and environments (Jenkins, GitLab CI, GitHub Actions).' },
      { topic: 'Containers (Docker)', detail: 'Images vs containers, Dockerfile layers, multi-stage builds, registries, and keeping images small and secure.' },
      { topic: 'Kubernetes', detail: 'Pods, Deployments, Services, ConfigMaps/Secrets, rolling updates, liveness/readiness probes and namespaces.' },
      { topic: 'Infrastructure as Code', detail: 'Terraform (declarative, state, plan/apply, modules) and Ansible for configuration - idempotent, version-controlled infra.' },
      { topic: 'Observability', detail: 'Metrics (Prometheus), dashboards (Grafana), centralized logs (ELK) and tracing. Watch the four golden signals.' },
      { topic: 'Cloud (AWS)', detail: 'EC2, S3, IAM roles/policies, VPC/subnets/security groups, load balancers and autoscaling.' },
      { topic: 'Linux & Networking', detail: 'Permissions, processes, systemd, shell scripting; DNS, TCP/IP, ports, TLS and firewalls.' },
      { topic: 'Reliability & Security', detail: 'Secrets management, least privilege, blue-green/canary releases, backups and SLO/SLA thinking.' },
    ],
    questions: [
      { q: 'What is the difference between a Docker image and a container?', a: 'An image is an immutable, layered template; a container is a running instance of that image with its own writable layer and isolated process namespace.' },
      { q: 'How does a Kubernetes rolling update achieve zero downtime?', a: 'It replaces old pods with new ones incrementally, respecting readiness probes and maxUnavailable/maxSurge, so traffic only routes to healthy pods.' },
      { q: 'What problem does Infrastructure as Code solve?', a: 'Reproducible, auditable, version-controlled infrastructure - it eliminates config drift and error-prone manual setup.' },
      { q: 'Liveness probe vs readiness probe?', a: 'Liveness restarts a hung container; readiness controls whether a pod is allowed to receive traffic.' },
      { q: 'Blue-green vs canary deployment?', a: 'Blue-green swaps all traffic between two identical environments at once; canary routes a small percentage to the new version first, then ramps up.' },
      { q: 'Why use multi-stage Docker builds?', a: 'Build tools and dependencies stay in an early stage; the final image copies only the artifact, producing a smaller, more secure image.' },
    ],
  },
  {
    id: 'java',
    label: 'Java Backend',
    blurb: 'Core Java, OOP, collections, concurrency, the JVM, and Spring Boot / JPA.',
    guide: [
      { topic: 'Core Java & OOP', detail: 'Encapsulation, inheritance, polymorphism, abstraction; interfaces vs abstract classes; the equals/hashCode contract.' },
      { topic: 'Collections', detail: 'List/Set/Map, ArrayList vs LinkedList, HashMap internals (buckets, load factor), and when to reach for TreeMap.' },
      { topic: 'Generics & Streams', detail: 'Type safety and bounded wildcards; Stream pipelines (map/filter/collect) and their laziness.' },
      { topic: 'Concurrency', detail: 'Thread vs Runnable, synchronized, volatile, ExecutorService and thread pools, deadlocks, CompletableFuture.' },
      { topic: 'JVM & Memory', detail: 'Heap vs stack, garbage collection generations, basic GC tuning and common causes of memory leaks.' },
      { topic: 'Exceptions', detail: 'Checked vs unchecked, try-with-resources, and designing meaningful custom exceptions.' },
      { topic: 'Spring Boot', detail: 'IoC/dependency injection, beans, @RestController/@Service/@Repository, profiles and auto-configuration.' },
      { topic: 'JPA / Hibernate', detail: 'Entities and relationships, lazy vs eager, transactions, derived queries and the N+1 problem.' },
    ],
    questions: [
      { q: 'What is the equals()/hashCode() contract?', a: 'Equal objects must return equal hashCodes. HashMap/HashSet rely on it; breaking it causes lost or duplicated entries.' },
      { q: 'ArrayList vs LinkedList?', a: 'ArrayList gives O(1) random access but costly mid-list inserts; LinkedList gives O(1) inserts/removes at the ends but O(n) access.' },
      { q: 'volatile vs synchronized?', a: 'volatile guarantees visibility of a variable across threads; synchronized provides both visibility and mutual exclusion (atomicity).' },
      { q: 'What is dependency injection in Spring?', a: 'The container creates and wires beans so a class declares its dependencies instead of constructing them - improving decoupling and testability.' },
      { q: 'Lazy vs eager loading in JPA?', a: 'Lazy fetches an association on first access; eager fetches it immediately. Lazy avoids over-fetching but can throw LazyInitializationException outside a transaction.' },
      { q: 'What causes the N+1 query problem and how do you fix it?', a: 'Loading a list then firing one query per element’s association. Fix with JOIN FETCH, entity graphs, or batch fetching.' },
    ],
  },
  {
    id: 'frontend',
    label: 'Frontend',
    blurb: 'HTML/CSS, modern JavaScript, React, state, performance and accessibility.',
    guide: [
      { topic: 'HTML & CSS', detail: 'Semantic HTML, the box model, Flexbox & Grid, specificity and responsive design.' },
      { topic: 'Modern JavaScript', detail: 'let/const, closures, promises and async/await, destructuring, modules, and the event loop.' },
      { topic: 'React Fundamentals', detail: 'Components, props, JSX, conditional rendering, and lists with stable keys.' },
      { topic: 'Hooks', detail: 'useState, useEffect (dependencies & cleanup), useMemo/useCallback, useRef and the rules of hooks.' },
      { topic: 'State Management', detail: 'Lifting state up, Context for shared state, and when a store (Redux/Zustand) is justified.' },
      { topic: 'Performance', detail: 'Reconciliation, memoization, code-splitting and avoiding unnecessary re-renders.' },
      { topic: 'Forms & Data', detail: 'Controlled inputs, fetch/axios, loading and error states, and debouncing input.' },
      { topic: 'Accessibility', detail: 'Semantic roles, labels, keyboard navigation, color contrast and ARIA basics.' },
    ],
    questions: [
      { q: 'Why do React lists need a key?', a: 'Keys give elements a stable identity so React can diff efficiently and preserve state across re-renders. Index keys break when items reorder.' },
      { q: 'What does the useEffect dependency array control?', a: 'When the effect re-runs: empty runs once on mount, with deps it runs when those change. Missing deps lead to stale closures.' },
      { q: 'Controlled vs uncontrolled component?', a: 'A controlled input’s value is driven by React state; an uncontrolled input is read from the DOM via a ref.' },
      { q: 'useMemo vs useCallback?', a: 'useMemo memoizes a computed value; useCallback memoizes a function reference. Both prevent needless recomputation or re-renders.' },
      { q: 'How does the browser event loop handle async work?', a: 'Synchronous code runs on the call stack; promise callbacks go on the microtask queue (after the current task); timers go on the macrotask queue.' },
      { q: 'Name one way to fix slow re-renders.', a: 'Memoize expensive children with React.memo, stabilize props with useCallback/useMemo, or split state so updates are localized.' },
    ],
  },
  {
    id: 'ai',
    label: 'AI / Python',
    blurb: 'Python, data handling, ML fundamentals, model evaluation and LLM/GenAI basics.',
    guide: [
      { topic: 'Python Core', detail: 'Data types, list/dict comprehensions, functions, generators, virtualenv/pip and error handling.' },
      { topic: 'NumPy & Pandas', detail: 'Vectorized arrays, DataFrames, indexing, groupby, joins and handling missing data.' },
      { topic: 'ML Fundamentals', detail: 'Supervised vs unsupervised, train/validation/test split, overfitting vs underfitting and the bias-variance trade-off.' },
      { topic: 'Core Algorithms', detail: 'Linear/logistic regression, decision trees & random forests, k-means, and the intuition behind gradient descent.' },
      { topic: 'Model Evaluation', detail: 'Accuracy vs precision/recall/F1, confusion matrix, ROC-AUC and cross-validation.' },
      { topic: 'Feature Engineering', detail: 'Scaling/normalization, encoding categoricals, and avoiding train/test leakage.' },
      { topic: 'Deep Learning Basics', detail: 'Neural networks, activation functions, epochs/batches and frameworks (PyTorch/TensorFlow).' },
      { topic: 'LLMs & GenAI', detail: 'Tokens, embeddings, prompting, retrieval-augmented generation (RAG), and evaluating hallucination.' },
    ],
    questions: [
      { q: 'What is overfitting and how do you reduce it?', a: 'The model memorizes training data and generalizes poorly. Reduce it with more data, regularization, simpler models, cross-validation or dropout.' },
      { q: 'When is accuracy a poor metric?', a: 'On imbalanced datasets - always predicting the majority class scores high. Use precision, recall, F1 or AUC instead.' },
      { q: 'Precision vs recall?', a: 'Precision: of predicted positives, how many are correct. Recall: of actual positives, how many were found.' },
      { q: 'What is RAG?', a: 'Retrieval-Augmented Generation: relevant documents are retrieved and given to an LLM as context so its answers are grounded and current.' },
      { q: 'Why split data into train/validation/test?', a: 'Train fits parameters, validation tunes hyperparameters and model choice, test gives an unbiased final estimate - preventing leakage and over-optimistic results.' },
      { q: 'What is an embedding?', a: 'A dense vector representation of text or data that captures semantic meaning, enabling similarity search and ML over unstructured inputs.' },
    ],
  },
]
