spring.application.name=governance-backend
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/citi_governance}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:governance}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:governance}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
