spring.application.name=governance-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/citi_governance
spring.datasource.username=governance
spring.datasource.password=governance

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
